# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity: { class: AppBundle\Entity\User, property: username }
    encoders:
        AppBundle\Entity\User:
            algorithm: sha1
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            security: false
            context: primary_auth

        main:
            pattern: ^/
            form_login:
                login_path: login
            anonymous: true
            context: primary_auth